polls_project/accounts/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    #path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
]

polls_project/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from polls import views as polls_views

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    path('polls/',include('polls.urls')),
    path('accounts/',include('accounts.urls')),
    path('about/',polls_views.AboutView.as_view(),name='about'),
]

polls_project/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    #THESE URLS ARE FOR CLASS BASED (GENERIC VIEWS)
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:pk>/create/choices', views.create_poll_view, name='choices'),
    path('create/', views.CreateQuestionView.as_view(), name='create'),
    path('<int:pk>/delete/', views.DeleteQuestionView.as_view(), name='delete'),
]

polls_project/accounts/models.py
from django.db import models

# Create your models here.

polls_project/polls/models.py
from django.db import models
from django.utils import timezone

from django.contrib.auth import get_user_model
User = get_user_model()

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Date Published',default=timezone.now)
    no_of_choices = models.IntegerField('Number of Choices', default=0)
    voted_by = models.ManyToManyField(User, blank=True, related_name='questions_voted')

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_total_votes(self):
        total_votes = 0
        for choice in self.choice_set.all():
            total_votes+=choice.votes
        return total_votes
#define a get leader instead
    def get_leader(self):
        total_votes = self.get_total_votes()
        if total_votes == 0:
            total_votes = 1
        leader = []
        choice = self.choice_set.all()[0]
        leader.append(choice.choice_text)
        leader.append(int((choice.votes/total_votes)*100))
        return leader

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        ordering = ['-votes']

    def __str__(self):
        return self.choice_text

polls_project/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

polls_project/accounts/views.py
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

polls_project/polls/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


class IndexView(generic.ListView):
    model = Question
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'


class AboutView(generic.TemplateView):
    template_name = 'about.html'


class DetailView(LoginRequiredMixin,generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


@login_required
def create_poll_view(request, pk):
    q = get_object_or_404(Question, pk=pk)
    n = q.no_of_choices
    if request.method == 'POST':
        for i in range(1,q.no_of_choices+1):
            q.choice_set.create(choice_text=request.POST['choice'+str(i)], votes=0)
        q.save()
        return(redirect(reverse('polls:index')))
    else:
        return(render(request,'polls/create_poll.html',
                                context={'question':q,'n':range(n)}))


class CreateQuestionView(LoginRequiredMixin,generic.edit.CreateView):
    model = Question
    fields = ['question_text', 'no_of_choices']
    login_url = '/'

    def get_success_url(self):
        return reverse('polls:choices', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeleteQuestionView(LoginRequiredMixin, generic.edit.DeleteView):
    model = Question
    success_url = reverse_lazy("polls:index")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        #changed start
        voted_by_user = request.user
        if voted_by_user in question.voted_by.all():
           return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        question.voted_by.add(voted_by_user)
        question.save()
        #changed end
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls_project/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-primary">
    </form>
</div>
{% endblock %}

polls_project/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-primary">
    </form>
</div>
{% endblock %}

polls_project/polls/templates/polls/_poll.html
<h1>{{ question.question_text }}</h1>
Published on: <time>{{question.pub_date}}</time>
<ul class="list-group">
{% for choice in question.choice_set.all %}
    <li class="list-group-item justify-content-between align-items-center d-flex">{{ choice.choice_text }}
      <span class="badge badge-primary badge-pill">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
    </li>
{% endfor %}
</ul>
<br>

<div class="media-footer">
  {% if user.is_authenticated and question.user == user and not hide_delete %}
    <a href="{% url 'polls:delete' pk=question.pk %}" title="delete" class="btn btn-simple">
      <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
      <span class="text-danger icon-label">Delete</span>
    </a>
  {% endif %}
</div>
{#<a class="btn btn-success" href="{% url 'polls:detail' question.id %}">Vote again?</a>#}

polls_project/polls/templates/polls/create_poll.html
{% extends "base.html" %}
{% block content %}
<h1>{{question.question_text}}?</h1>
<form class="" action="{% url 'polls:choices' question.pk %}" method="post">
  {% csrf_token %}
  {% for choice in n %}
  <div class="form-group">
    <label for="choice{{ forloop.counter }}">Choice {{forloop.counter}}:</label>
    <input type="text" class="form-control" name="choice{{forloop.counter}}">
  </div>
  {% endfor %}
  <input class="btn btn-success" type="submit" name="submit" value="Create Poll">
</form>
{% endblock %}

polls_project/polls/templates/polls/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ question.question_text }}?</h1>
<small class="form-text text-muted">Published on:
  <i class="fas fa-clock"></i>
  <time>{{question.pub_date}}</time>
</small>
<br>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
<div style="border-radius:10px" class="list-group-item">
  <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
  <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
</div>
{% endfor %}
<br>
<input type="submit" class="btn btn-success" value="Vote">
</form>

{% endblock %}

polls_project/polls/templates/polls/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
{% if latest_question_list %}
  {% for question in latest_question_list %}
  <br>
  <div class="rcorners2 shadow">
      <h2>{{question.question_text}}?</h2>
      <small class="form-text text-muted">Published on:
        <i class="fas fa-clock"></i>
        <time>{{question.pub_date}}</time>
      </small>
      <br>
      <p>Total Votes: {{question.get_total_votes}} </p>
      {% if user.is_authenticated %}
      {% if question in user.questions_voted.all %}
      <button type="button" class="btn btn-secondary" disabled>
        <i class="far fa-check-circle"></i>
        Voted
      </button>
      {% else %}
      <a type="button" href="{% url 'polls:detail' question.id %}" class="btn btn-success">
        Vote!
      </a>
      {% endif %}
      {% if question.user == user %}
      <a type="button" href="{% url 'polls:delete' question.id %}" class="btn btn-danger">
        <i class="fas fa-trash-alt"></i>
        Delete
      </a>
      {% endif %}
      {% endif %}
      <a type="button" href="{% url 'polls:results' question.id %}" class="btn btn-primary">
        View Results
      </a>
      <hr>
      Leader:
      <div class="progress" style="height: 50px;">
          <div class="progress-bar progress-bar bg-danger" role="progressbar" style="width:{{question.get_leader.1}}%">
            {{question.get_leader.0}}: {{question.get_leader.1}}%
          </div>
      </div>
  </div>
  <br>
{% endfor %}

{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

polls_project/polls/templates/polls/question_confirm_delete.html
{% extends "base.html" %}


{% block content %}
<h3>Are you sure you want to delete this poll?</h3>

<div class="posts">
	{% include "polls/_poll.html" with question=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'polls:results' pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

polls_project/polls/templates/polls/question_form.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-success" type="submit" value="Enter Choices">
</form>

{% endblock %}

polls_project/polls/templates/polls/results.html
{% extends "base.html" %}
{% block content %}
<h1>{{ question.question_text }}?</h1>
<small class="form-text text-muted">Published on:
  <i class="fas fa-clock"></i>
  <time>{{question.pub_date}}</time>
</small>
<br>
<ul class="list-group">
{% for choice in question.choice_set.all %}
    <li class="list-group-item justify-content-between align-items-center d-flex">{{ choice.choice_text }}
      <span class="badge badge-primary badge-pill">{{ choice.votes }} vote{{ choice.votes|pluralize }}</span>
    </li>
{% endfor %}
</ul>
<br>

<div class="media-footer">
  {% if user.is_authenticated and question.user == user and not hide_delete %}
    <a href="{% url 'polls:delete' pk=question.pk %}" title="delete" class="btn btn-danger">
      <i class="fas fa-trash-alt"></i>Delete
    </a>
  {% endif %}
</div>
{% endblock %}

polls_project/templates/about.html
{% extends "base.html" %}
{% block content %}
  <h1>About Us</h1>
  <p>Using this application, you can create your own polls and reach to other users for their opinions.</p>
  <p>You can also vote for other polls.</p>
  <p>Please <a href="{% url 'login' %}">Login</a> to use the app.</p>
  <p>Or <a href="{% url 'accounts:signup' %}">Sign Up</a> if you are a new user.</p>
{% endblock %}

polls_project/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Polls App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {# TITLE FONT #}
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">
    {#ICONS#}
    <script src="https://kit.fontawesome.com/cb50fdb1a6.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light ">
        <div class="container">
          <a class="navbar-brand" href="{% url 'polls:index' %}">
            <i class="fas fa-home"></i>
            Home
          </a>
          <h1 style="font-family: 'Indie Flower', cursive;">PollsApp</h1>
          <ul class="nav navbar-nav nav-fill">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'polls:create' %}">
              <i class="fas fa-plus"></i>
              Create Poll
              </a>
            </li class="nav-item">
            <li class="nav-item nav-link">Welcome: {{user.username}}</li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>

            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    <div class="container">
      <br>
      {% block content %}

      {% endblock %}
      <br>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>